name: svpcet
description: A simple Flutter app for SVPCET with a yellow Start Now button.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logosvpcet.png
    - assets/home1.jpg
    - assets/home2.jpg
    - assets/home3.jpg
    - assets/home4.jpg
    - assets/home5.jpg
    - assets/home6.jpg
    - assets/home7.jpg
    - assets/images/calenderodd.jpg
    - assets/images/calendereven.jpg
